# Generated by Django 2.0 on 2018-01-31 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('production_date', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=250)),
                ('director', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=10000)),
                ('rate', models.CharField(max_length=100)),
                ('trailer_url', models.CharField(max_length=1000)),
                ('movie_logo', models.CharField(max_length=1000)),
            ],
        ),
    ]
