# Generated by Django 2.0.1 on 2018-02-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='production_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rate',
            field=models.IntegerField(),
        ),
    ]
