# Generated by Django 2.0 on 2018-02-02 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_logo',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
