# Generated by Django 2.0 on 2018-02-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20180202_0232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('genre', models.CharField(max_length=500)),
                ('sort', models.CharField(max_length=500)),
            ],
        ),
    ]
