# Generated by Django 2.0 on 2018-02-03 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_search'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
