# Generated by Django 2.0 on 2018-02-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0002_auto_20180205_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='profile_image'),
        ),
    ]
