# Generated by Django 2.0 on 2018-02-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0003_auto_20180205_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(upload_to='profile_image'),
        ),
    ]
