# Generated by Django 2.0.1 on 2018-02-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0005_auto_20180205_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQa5Ej3441nczWsWFHcl2NS9bii3fwY3pBUcr-4fdAtmXUn9MEMQ', upload_to='profile_image'),
        ),
    ]
