# Generated by Django 2.0.1 on 2018-02-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0006_auto_20180205_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='profile_image/default_profile.png', upload_to='profile_image'),
        ),
    ]
