# Generated by Django 2.0.2 on 2018-02-02 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0007_auto_20180202_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='user',
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
